module.exports = {
  databaseName: 'EPCMsystem',
  username: 'xzy',
  pwd: 'xzy',
  host: 'localhost',
  port: '27017',
  signature: 'xzy',
  expiresIn: 24 * 60 * 60,
  ultraVires: 700,
  tokenExpireCode: 600,
  tokenExpireText: 'token已过期，请重新登录',
  noUserText: '该用户不存在',
  noUserCode: 800,
  addArticleText: '公告添加成功',
  hasArticle: '该公告名称已存在',
  addUserText: '成功创建用户',
  hadUser: '该账号已被注册，请重新编辑账号再进行注册',
  deleteUserText: '成功删除该用户',
  updateUserText: '成功修改用户信息',
  addApplyText: '成功添加外出申请记录',
  hadApplyText: '您当前已经有外出申请了',
  noApplyText: '没有该申请记录'
}
